version: '3'

services:
  client:
    build:
      context: "."
      dockerfile: "./docker/client/Dockerfile"
    container_name: client
    volumes:
      - ./client:/app
      - exclude:/app/node_modules/
    ports:
      - "3000:5180"
    depends_on:
      - php-fpm
    networks:
      - public_net
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./backend:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: 'on-failure'
    depends_on:
      - php-fpm
      - db
    networks:
      - public_net
  php-fpm:
    container_name: laravel-api
    build:
      args:
        uname: dev
        uid: 1000
        gid: 1000
      context: "./docker"
      dockerfile: "php/Dockerfile"
    volumes:
      - ./backend:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: 'on-failure'
    networks:
      - public_net
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
        - SYS_NICE
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - data-db:/var/lib/mysql
    networks:
      - public_net

volumes:
  exclude:
  data-db:
networks:
    public_net:
        driver: bridge