name: Laravel
on:
  push:
    branches: [ "main" ]
jobs:
  #laravel-tests:
    #runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: backend
    # steps:
    # - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    #   with:
    #     php-version: '8.3'
    # - uses: actions/checkout@v4
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    # - name: Install Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate key
    #   run: php artisan key:generate
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache
    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite
    # - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: php artisan test
  # deploy:
  #     name: Build and Deploy
  #     #needs: laravel-tests
  #     runs-on: ubuntu-latest
  #     defaults:
  #       run:
  #         working-directory: backend
  #     steps:
  #         - name: Checkout Repository
  #           uses: actions/checkout@master
  #         - name: Setup Enviroment
  #           uses: shivammathur/setup-php@v2
  #           with:
  #             php-version: '8.3'
  #         - name: Install Packages
  #           run: composer install --no-dev

  #         # - name: create storage link
  #           # run: php artisan storage:link
  #         # - name: Copy production env
  #         #   run: cp .env.production .env
  #         # - name: create app key
  #         #   run: php artisan key:generate
  #         - name: Deploy to Server
  #           uses: ngocquyhoang/deploy@laravel
  #           with:
  #             user: ubuntu
  #             host: ${{ secrets.SERVER_HOST }}
  #             port: 22
  #             path: /var/www/html/api
  #             owner: ubuntu
  #           env:
  #             DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ubuntu
            port: 22
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
            cd /var/www/html/api && 
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan env:decrypt --env=production --key="${{ secrets.ENV_SECRET }}" &&
            ./deploy.sh